# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Automated Releases by Tag

on:
  push:
    branches: [ "master" ]
    tags: [ "v[0-9]+.[0-9]+.[0-9]+" ]
  pull_request:
    branches: [ "master" ]
  workflow_run:
    workflows: ["Build Executable .jar", "CI Tests and Reports"]

permissions:
  contents: read

jobs:
  releases:
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-2022]
    runs-on: ${{ matrix.os }}
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: 'temurin'
        
    - name: Download a Ubuntu Build Artifact
      uses: actions/download-artifact@v3.0.1
      with:
        name: piazzapanic-ubuntu-22.04.jar
        
    - name: Release Ubuntu
      uses: softprops/action-gh-release@v1
      with:
        files: piazzapanic-ubuntu-22.04.jar
        
    - name: Download a Windows Build Artifact
      uses: actions/download-artifact@v3.0.1
      with:
        name: piazzapanic-windows-2022.jar
        
    - name: Release Ubuntu
      uses: softprops/action-gh-release@v1
      with:
        files: piazzapanic-windows-2022.jar
